package com.pipeline.stages;

import java.io.*;
import java.nio.file.*;

public class AudioTextStage {

    private final String inputFile;
    private final String outputDir;

    public AudioTextStage(String inputFile, String outputDir) {
        this.inputFile = inputFile;
        this.outputDir = outputDir;
    }

    public void run() throws Exception {
        System.out.println("\n── Phase 4: AUDIO / TEXT ────────────────────────");

        String transcript   = speechToText();
        String translation  = translate(transcript);
        generateDub(translation);

        System.out.println(" Audio/Text complete.\n");
    }

    private String speechToText() throws IOException, InterruptedException {
        System.out.print("  [Speech-to-Text] Transcribing audio... ");
        Thread.sleep(500);

        String transcript =
            "00:00:00 --> 00:00:05\n" +
            "Welcome to the world of tomorrow.\n\n" +
            "00:00:06 --> 00:00:12\n" +
            "This is a stub transcript generated by the pipeline.\n\n" +
            "00:00:13 --> 00:00:20\n" +
            "In a real system, a speech recognition model would be used here.\n";

        String textDir = outputDir + "/text";
        Files.createDirectories(Path.of(textDir));
        String outPath = textDir + "/source_transcript.txt";
        try (FileWriter fw = new FileWriter(outPath)) {
            fw.write(transcript);
        }

        System.out.println("✓");
        System.out.println("  [Speech-to-Text] ✓ source_transcript.txt saved → " + outPath);
        return transcript;
    }

    private String translate(String transcript) throws IOException, InterruptedException {
        System.out.print("  [Translator] Translating to Romanian (ro)... ");
        Thread.sleep(400);

        String translation =
            "00:00:00 --> 00:00:05\n" +
            "Bun venit în lumea de mâine.\n\n" +
            "00:00:06 --> 00:00:12\n" +
            "Acesta este un transcript generat de pipeline.\n\n" +
            "00:00:13 --> 00:00:20\n" +
            "Într-un sistem real, s-ar folosi un model de recunoaștere a vorbirii.\n";

        String outPath = outputDir + "/text/ro_translation.txt";
        try (FileWriter fw = new FileWriter(outPath)) {
            fw.write(translation);
        }

        System.out.println("✓");
        System.out.println("  [Translator] ✓ ro_translation.txt saved → " + outPath);
        return translation;
    }

    private void generateDub(String translation) throws IOException, InterruptedException {
        System.out.print("  [AI Dubber] Generating synthetic Romanian dub... ");
        Thread.sleep(600);

        String audioDir = outputDir + "/audio";
        Files.createDirectories(Path.of(audioDir));
        String outPath = audioDir + "/ro_dub_synthetic.aac";
        try (FileWriter fw = new FileWriter(outPath)) {
            fw.write("STUB_AAC_DUB — ro\n");
            fw.write("In a real system this would be generated by a TTS/dubbing model.\n");
        }

        System.out.println("✓");
        System.out.println("  [AI Dubber] ✓ ro_dub_synthetic.aac saved → " + outPath);
    }
}
